package com.ovi.tradingbeast;

import android.app.*;
import android.os.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
    static final String BASE="http://127.0.0.1:8765";
    static final int BG=Color.rgb(8,12,18), CARD=Color.rgb(18,25,34), CARD2=Color.rgb(22,30,41), TEXT=Color.rgb(242,246,250), MUTED=Color.rgb(151,166,181), GREEN=Color.rgb(48,205,137), BLUE=Color.rgb(83,145,224), RED=Color.rgb(221,73,88), GOLD=Color.rgb(210,164,76), BORDER=Color.rgb(42,54,68);
    LinearLayout content; TextView status, health, balance, portfolio, positions, signal, performance, activityLog, message, updated, allocationLabel;
    EditText amount, maxProjects; Spinner mode; ExecutorService pool=Executors.newFixedThreadPool(3); Handler handler=new Handler(Looper.getMainLooper());
    int lastEntries=-1,lastTP=-1; boolean firstState=true;
    int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    TextView text(String s,float size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(dp(2),dp(2),dp(2),dp(2));return t;}
    GradientDrawable bg(int color,float radius,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));if(stroke>0)g.setStroke(dp(1),BORDER);return g;}
    LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);l.setWeightSum(2);return l;}
    LinearLayout card(String title){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(15),dp(16),dp(15));c.setBackground(bg(CARD,18,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(12));c.setLayoutParams(lp);TextView h=text(title,13,MUTED);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setLetterSpacing(.08f);c.addView(h);return c;}
    Button button(String label,int color){Button b=new Button(this);b.setText(label);b.setTextColor(Color.WHITE);b.setTextSize(13);b.setAllCaps(false);b.setMinHeight(dp(50));b.setBackground(bg(color,14,0));b.setPadding(dp(8),0,dp(8),0);b.setLayoutParams(new LinearLayout.LayoutParams(0,dp(54),1));b.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_DOWN)v.setAlpha(.68f);if(e.getAction()==MotionEvent.ACTION_UP||e.getAction()==MotionEvent.ACTION_CANCEL)v.setAlpha(1f);return false;});return b;}
    TextView value(String s){TextView t=text(s,20,TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);build();requestNotificationPermission();refresh();handler.postDelayed(poller,5000);}
    Runnable poller=new Runnable(){public void run(){refresh();handler.postDelayed(this,5000);}};
    void requestNotificationPermission(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},41);}
    void notifyEvent(String title,String body){if(Build.VERSION.SDK_INT>=26){NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);nm.createNotificationChannel(new NotificationChannel("trading","Trading activity",NotificationManager.IMPORTANCE_DEFAULT));Intent i=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification n=new Notification.Builder(this,"trading").setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle(title).setContentText(body).setContentIntent(pi).setAutoCancel(true).build();nm.notify((int)(System.currentTimeMillis()%100000),n);}Toast.makeText(this,title+" — "+body,Toast.LENGTH_LONG).show();}
    void build(){ScrollView sc=new ScrollView(this);sc.setBackgroundColor(BG);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(18),dp(18),dp(18),dp(32));sc.addView(content);setContentView(sc);
        TextView brand=text("OVI PLUS",30,GREEN);brand.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(brand);TextView title=text("TRADING BEAST",18,TEXT);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(title);TextView sub=text("SOLANA DIGITAL ASSET COMMAND CENTER",11,MUTED);sub.setPadding(0,dp(2),0,dp(16));content.addView(sub);
        LinearLayout online=card("ACCOUNT & ENGINE");LinearLayout top=row();status=value("CONNECTING…");top.addView(status,new LinearLayout.LayoutParams(0,-2,1));health=text("●",20,MUTED);health.setGravity(Gravity.RIGHT);top.addView(health,new LinearLayout.LayoutParams(dp(60),-2));online.addView(top);TextView modeText=text("Paper trading • execution safeguards active",12,MUTED);online.addView(modeText);content.addView(online);
        LinearLayout port=card("PORTFOLIO OVERVIEW");balance=value("Paper balance • —");portfolio=text("Active capital: —     Positions: —",13,MUTED);port.addView(balance);port.addView(portfolio);content.addView(port);
        LinearLayout alloc=card("TRADING PLAN");LinearLayout ar=row();amount=new EditText(this);amount.setTextColor(TEXT);amount.setHintTextColor(MUTED);amount.setHint("0.001");amount.setTextSize(17);amount.setInputType(8194);ar.addView(text("Allocation (SOL)",14,MUTED),new LinearLayout.LayoutParams(0,dp(52),1));ar.addView(amount,new LinearLayout.LayoutParams(dp(130),dp(52)));alloc.addView(ar);LinearLayout br=row();mode=new Spinner(this);mode.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"SINGLE","MULTIPLE"}));maxProjects=new EditText(this);maxProjects.setTextColor(TEXT);maxProjects.setHintTextColor(MUTED);maxProjects.setHint("1");maxProjects.setTextSize(16);maxProjects.setInputType(2);br.addView(text("Position mode",14,MUTED),new LinearLayout.LayoutParams(0,dp(52),1));br.addView(mode,new LinearLayout.LayoutParams(dp(120),dp(52)));br.addView(maxProjects,new LinearLayout.LayoutParams(dp(65),dp(52)));alloc.addView(br);Button save=button("Save trading plan",Color.rgb(31,108,77));save.setOnClickListener(v->saveSettings());alloc.addView(save);content.addView(alloc);
        LinearLayout scan=card("SCANNER INTELLIGENCE");signal=text("Waiting for live scanner data…",14,TEXT);scan.addView(signal);TextView rules=text("Entry filter • liquidity • volume • buy ratio • token age • security checks",11,MUTED);rules.setPadding(0,dp(8),0,0);scan.addView(rules);content.addView(scan);
        LinearLayout pos=card("ACTIVE POSITIONS");positions=text("No active paper position",14,MUTED);pos.addView(positions);content.addView(pos);
        LinearLayout perf=card("PERFORMANCE");performance=text("Entries: 0   •   Take profits: 0   •   Rejected: 0",14,TEXT);perf.addView(performance);content.addView(perf);
        LinearLayout activity=card("LIVE ACTIVITY");activityLog=text("Waiting for scanner output…",12,MUTED);activityLog.setTypeface(Typeface.MONOSPACE);activityLog.setMaxLines(80);activityLog.setBackground(bg(CARD2,12,0));activity.addView(activityLog);content.addView(activity);
        LinearLayout controls=card("BOT CONTROLS");LinearLayout r1=row();Button start=button("START",Color.rgb(27,133,91)),stop=button("STOP",Color.rgb(113,49,61));r1.addView(start);r1.addView(stop);controls.addView(r1);LinearLayout r2=row();Button restart=button("RESTART",Color.rgb(43,91,143)),em=button("EMERGENCY STOP",RED);r2.addView(restart);r2.addView(em);controls.addView(r2);LinearLayout r3=row();Button resume=button("RESUME",Color.rgb(43,91,143)),fresh=button("SCAN FRESH",Color.rgb(122,92,36));r3.addView(resume);r3.addView(fresh);controls.addView(r3);Button refresh=button("REFRESH NOW",Color.rgb(42,50,62));controls.addView(refresh);start.setOnClickListener(v->action("/start"));stop.setOnClickListener(v->action("/stop"));restart.setOnClickListener(v->action("/restart"));em.setOnClickListener(v->action("/emergency-stop"));resume.setOnClickListener(v->action("/resume"));fresh.setOnClickListener(v->action("/scan"));refresh.setOnClickListener(v->refresh());content.addView(controls);
        LinearLayout sys=card("SYSTEM STATUS");message=text("Bridge: connecting…",12,MUTED);updated=text("Last update: —",11,MUTED);sys.addView(message);sys.addView(updated);content.addView(sys);
    }
    void action(String path){pool.execute(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(BASE+path).openConnection();c.setRequestMethod("POST");c.setConnectTimeout(3000);c.setReadTimeout(5000);c.setDoOutput(true);c.getOutputStream().write("{}".getBytes("UTF-8"));int code=c.getResponseCode();runOnUiThread(()->{message.setText("Command "+path+" accepted • HTTP "+code);refresh();});}catch(Exception e){runOnUiThread(()->message.setText("Command failed: "+e.getMessage()));}});}
    void saveSettings(){try{double v=Double.parseDouble(amount.getText().toString().trim());int m=Integer.parseInt(maxProjects.getText().toString().trim().isEmpty()?"1":maxProjects.getText().toString().trim());String body="{\"trade_amount\":"+v+",\"position_mode\":\""+mode.getSelectedItem().toString()+"\",\"max_active_projects\":"+m+"}";pool.execute(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(BASE+"/settings").openConnection();c.setRequestMethod("POST");c.setDoOutput(true);c.getOutputStream().write(body.getBytes("UTF-8"));int code=c.getResponseCode();runOnUiThread(()->message.setText("Trading plan saved • HTTP "+code));refresh();}catch(Exception e){runOnUiThread(()->message.setText("Settings failed: "+e.getMessage()));}});}catch(Exception e){message.setText("Enter a valid SOL amount and project limit.");}}
    void refresh(){pool.execute(()->{try{JSONObject all=getJson(BASE+"/status"),st=all.getJSONObject("state"),set=all.getJSONObject("settings"),stats=st.getJSONObject("stats");int e=stats.optInt("entries"),tp=stats.optInt("take_profits");runOnUiThread(()->{String ss=st.optString("status","OFFLINE");status.setText(("ONLINE".equals(st.optString("health"))?"● ":"○ ")+ss);status.setTextColor("ONLINE".equals(st.optString("health"))?GREEN:RED);health.setText("ONLINE".equals(st.optString("health"))?"●":"○");health.setTextColor("ONLINE".equals(st.optString("health"))?GREEN:RED);balance.setText("Paper trading • "+String.format(Locale.US,"%.6f",set.optDouble("trade_amount",0.001))+" SOL / project");portfolio.setText("Active positions: "+(st.optJSONArray("positions")!=null?st.optJSONArray("positions").length():0)+"     Mode: "+set.optString("position_mode"));amount.setText(String.valueOf(set.optDouble("trade_amount",0.001)));maxProjects.setText(String.valueOf(set.optInt("max_active_projects",1)));mode.setSelection("MULTIPLE".equals(set.optString("position_mode"))?1:0);positions.setText(formatPositions(st.optJSONArray("positions")));signal.setText(formatSignal(st.optJSONObject("latest_signal")));performance.setText("Entries: "+e+"   •   Take profits: "+tp+"   •   Rejected: "+stats.optInt("rejected"));message.setText(st.optBoolean("emergency_stop",false)?"EMERGENCY STOP ACTIVE • new entries blocked":"Bridge connected • paper execution only • signing OFF • broadcast OFF");updated.setText("Last update: "+new Date());if(!firstState&&e>lastEntries)notifyEvent("TRADE ENTERED","Paper position opened");if(!firstState&&tp>lastTP)notifyEvent("TAKE PROFIT","Paper position closed at target");lastEntries=e;lastTP=tp;firstState=false;});loadLogs();}catch(Exception ex){runOnUiThread(()->{status.setText("○ BRIDGE OFFLINE");status.setTextColor(RED);health.setText("○");health.setTextColor(RED);message.setText("Open Termux bridge: android_app/server.py");});}});}
    JSONObject getJson(String url)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(3000);c.setReadTimeout(5000);BufferedReader br=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder s=new StringBuilder();String l;while((l=br.readLine())!=null)s.append(l);return new JSONObject(s.toString());}
    String formatSignal(JSONObject o){if(o==null)return "No qualified project yet • scanner is active";return "Candidate: "+o.optString("symbol","UNKNOWN")+"\nScore: "+o.optDouble("score",0)+"   Buy ratio: "+o.optDouble("buy_ratio",0)+"%\nPrice: $"+o.optString("price_usd","—");}
    String formatPositions(JSONArray a){if(a==null||a.length()==0)return "No active paper position";StringBuilder s=new StringBuilder();for(int i=0;i<a.length();i++){JSONObject p=a.optJSONObject(i);if(p!=null)s.append(p.optString("symbol","UNKNOWN")).append("  •  ").append(p.optDouble("amount_sol",0)).append(" SOL  •  ENTRY\n");}return s.toString();}
    void loadLogs(){pool.execute(()->{try{JSONObject o=getJson(BASE+"/logs");JSONArray a=o.optJSONArray("lines");StringBuilder s=new StringBuilder();if(a!=null){int start=Math.max(0,a.length()-100);for(int i=start;i<a.length();i++)s.append(a.optString(i)).append("\n");}String out=s.length()==0?"Waiting for scanner output…":s.toString();runOnUiThread(()->activityLog.setText(out));}catch(Exception ignored){}});}
    @Override protected void onDestroy(){handler.removeCallbacks(poller);pool.shutdownNow();super.onDestroy();}
}
