BOT_NAME = "Solana New Meme Bot"

PAPER_TRADING = True

TAKE_PROFIT_PERCENT = 17.0
STOP_LOSS_ENABLED = False
ONE_POSITION_AT_A_TIME = True

MAX_TOKEN_AGE_MINUTES = 230400

MIN_LIQUIDITY_USD = 5000
MIN_VOLUME_5M_USD = 250

REQUIRE_MINT_AUTHORITY_REVOKED = True
REQUIRE_FREEZE_AUTHORITY_REVOKED = True
MAX_TOP_HOLDERS_PERCENT = 20.0

STORE_PASSED_TOKENS = False

PRICE_CHECK_INTERVAL_SECONDS = 5

MAX_DAILY_LOSS_USD = 25.0
MIN_TOKEN_AGE_MINUTES = 360
